client:client.cpp
	g++ -pthread -g -o client client.cpp

server:server.cpp
	g++ -pthread -o server server.cpp


# 3:client3.cpp
# 	g++ -pthread -o client3 client3.cpp


# test:client_test.cpp
# 	g++ -pthread -o test client_test.cpp


# draft:client_draft.cpp
# 	g++ -pthread -o draft client_draft.cpp